spring:
  cloud:
    gateway:
      routes:
        - id: login-route
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: oauth2-route
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/oauth2/**

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0
      login-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 60s
        timeoutDuration: 0