spring:
  application:
    name: transaction-service

  cloud:
    config:
      enabled: false

  config:
    import: ""

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  rabbitmq:
    listener:
      simple:
        auto-startup: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    enabled-by-default: false